version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - .data/postgres:/var/lib/postgresql/data/

  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - "6379:6379"

  wkhtmltopdf:
    container_name: wkhtmltopdf-aas
    image: "openlabs/docker-wkhtmltopdf-aas"
    ports:
      - "4133:80"
    restart: unless-stopped
    volumes:
      - .:/data