# Generated by Django 4.2.3 on 2023-07-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=67)),
                ("api_key", models.CharField(blank=True, max_length=67, unique=True)),
                (
                    "check_type",
                    models.CharField(
                        choices=[("kitchen", "Kitchen"), ("client", "Client")],
                        max_length=67,
                    ),
                ),
                ("point_id", models.IntegerField()),
            ],
            options={
                "unique_together": {("check_type", "point_id")},
            },
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("kitchen", "Kitchen"), ("client", "Client")],
                        max_length=67,
                    ),
                ),
                ("order", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("rendered", "Rendered"),
                            ("printed", "Printed"),
                        ],
                        default="new",
                        max_length=67,
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="check_service.printer",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
